[build]
  command = "npm run build" # your build command
  publish = "./dist" # where your production ready client code lives AFTER your build command has run
  ### functions = "./functions" # where your production ready lambda functions live AFTER your build command has run

[functions]
  directory = "./functions"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "child-src 'self' app.netlify.com; script-src 'self' app.netlify.com netlify-cdp-loader.netlify.app;"

[[redirects]]
  from = "/initialize"
  to = "/.netlify/functions/initialize"
  status = 200
[[redirects]]
  from = "/refresh-data"
  to = "/.netlify/functions/refresh-data"
  status = 200
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
