name: Deploy Cloudflare Worker Production
on:
  push:
    branches:
      - master
jobs:
  Deploy-Cloudflare-Worker-Production-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
#       - name: Deploy to Cloudflare Workers with Wrangler
#         uses: cloudflare/wrangler-action@1.2.0
